import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  decryptSecrets,
  detectRequiredSecrets,
  encryptSecrets,
  exportToEnv,
  exportToYaml,
  importFromEnv,
  importFromYaml,
  maskValue,
  type SecretsData,
} from "../../../src/lib/secrets.js";

describe("secrets command logic", () => {
  let testDir: string;

  beforeEach(() => {
    testDir = join(tmpdir(), `cin-secrets-cmd-test-${Date.now()}`);
    mkdirSync(testDir, { recursive: true });
  });

  afterEach(() => {
    if (existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true });
    }
  });

  describe("secrets setup", () => {
    it("should detect required secrets from docker-compose.yml", () => {
      const composePath = join(testDir, "docker-compose.yml");
      writeFileSync(
        composePath,
        `
services:
  api:
    environment:
      - DATABASE_URL
      - API_KEY
      - REDIS_URL=redis://localhost
  worker:
    environment:
      SECRET_TOKEN:
      DEBUG: "false"
`
      );

      const required = detectRequiredSecrets(composePath);

      expect(required).toContain("DATABASE_URL");
      expect(required).toContain("API_KEY");
      expect(required).toContain("SECRET_TOKEN");
      expect(required).not.toContain("REDIS_URL");
      expect(required).not.toContain("DEBUG");
    });

    it("should handle missing compose file", () => {
      const required = detectRequiredSecrets(join(testDir, "nonexistent.yml"));
      expect(required).toEqual([]);
    });

    it("should handle compose without services", () => {
      const composePath = join(testDir, "docker-compose.yml");
      writeFileSync(composePath, "version: '3.8'\n");

      const required = detectRequiredSecrets(composePath);
      expect(required).toEqual([]);
    });
  });

  describe("secrets import", () => {
    it("should import from .env file", () => {
      const envPath = join(testDir, ".env");
      writeFileSync(
        envPath,
        `
# Database config
DATABASE_URL=postgres://localhost:5432/db
API_KEY=secret123

# Redis
REDIS_URL=redis://localhost:6379
`
      );

      const secrets = importFromEnv(envPath);

      expect(secrets.DATABASE_URL).toBe("postgres://localhost:5432/db");
      expect(secrets.API_KEY).toBe("secret123");
      expect(secrets.REDIS_URL).toBe("redis://localhost:6379");
    });

    it("should import from YAML file", () => {
      const yamlPath = join(testDir, "secrets.yaml");
      writeFileSync(
        yamlPath,
        `
secrets:
  DATABASE_URL: postgres://localhost:5432/db
  API_KEY: secret123
`
      );

      const secrets = importFromYaml(yamlPath);

      expect(secrets.DATABASE_URL).toBe("postgres://localhost:5432/db");
      expect(secrets.API_KEY).toBe("secret123");
    });

    it("should handle quoted values in .env", () => {
      const envPath = join(testDir, ".env");
      writeFileSync(
        envPath,
        `
DOUBLE_QUOTED="value with spaces"
SINGLE_QUOTED='another value'
UNQUOTED=simple
`
      );

      const secrets = importFromEnv(envPath);

      expect(secrets.DOUBLE_QUOTED).toBe("value with spaces");
      expect(secrets.SINGLE_QUOTED).toBe("another value");
      expect(secrets.UNQUOTED).toBe("simple");
    });
  });

  describe("secrets export", () => {
    it("should export to .env format", () => {
      const secrets: SecretsData = {
        API_KEY: "secret123",
        DATABASE_URL: "postgres://localhost/db",
      };

      const output = exportToEnv(secrets);

      expect(output).toContain("API_KEY=secret123");
      expect(output).toContain("DATABASE_URL=postgres://localhost/db");
      expect(output).toContain("# Generated by CIN CLI");
    });

    it("should export to YAML format", () => {
      const secrets: SecretsData = {
        API_KEY: "secret123",
        DATABASE_URL: "postgres://localhost/db",
      };

      const output = exportToYaml(secrets);

      expect(output).toContain("secrets:");
      expect(output).toContain('API_KEY: "secret123"');
      expect(output).toContain('DATABASE_URL: "postgres://localhost/db"');
    });

    it("should quote values with special characters", () => {
      const secrets: SecretsData = {
        SIMPLE: "simple",
        WITH_SPACE: "has space",
        WITH_DOLLAR: "value$var",
      };

      const output = exportToEnv(secrets);

      expect(output).toContain("SIMPLE=simple");
      expect(output).toContain('WITH_SPACE="has space"');
      expect(output).toContain('WITH_DOLLAR="value$var"');
    });
  });

  describe("secrets encryption", () => {
    it("should encrypt and decrypt secrets", () => {
      const secrets: SecretsData = {
        API_KEY: "super-secret-key",
        PASSWORD: "p@ssw0rd!",
      };

      const encrypted = encryptSecrets(secrets);
      const decrypted = decryptSecrets(encrypted);

      expect(decrypted).toEqual(secrets);
    });

    it("should produce different ciphertext each time", () => {
      const secrets: SecretsData = { KEY: "value" };

      const enc1 = encryptSecrets(secrets);
      const enc2 = encryptSecrets(secrets);

      expect(enc1.encrypted).not.toBe(enc2.encrypted);
      expect(enc1.iv).not.toBe(enc2.iv);
    });

    it("should include all required fields", () => {
      const secrets: SecretsData = { KEY: "value" };
      const encrypted = encryptSecrets(secrets);

      expect(encrypted.encrypted).toBeDefined();
      expect(encrypted.iv).toBeDefined();
      expect(encrypted.salt).toBeDefined();
      expect(encrypted.authTag).toBeDefined();
    });
  });

  describe("secrets list/mask", () => {
    it("should mask short values", () => {
      expect(maskValue("abc")).toBe("****");
      expect(maskValue("1234")).toBe("****");
    });

    it("should mask long values showing first and last 2 chars", () => {
      expect(maskValue("secret123")).toBe("se****23");
      expect(maskValue("longsecretvalue")).toBe("lo****ue");
    });
  });

  describe("secrets check", () => {
    it("should identify missing secrets", () => {
      const required = ["API_KEY", "DB_PASS", "SECRET"];
      const configured: SecretsData = {
        API_KEY: "configured",
        DB_PASS: "configured",
      };

      const missing = required.filter((key) => !(key in configured));
      const present = required.filter((key) => key in configured);

      expect(missing).toEqual(["SECRET"]);
      expect(present).toEqual(["API_KEY", "DB_PASS"]);
    });
  });
});
